version: "1.0"

services:
  mongo:
    container_name: connect_db
    image: mongo
    restart: always
    networks:
      - store-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_volume:/data/db
    ports:
      - ${MG_PORTS}:${MG_PORTS}
    env_file: .env

  mongo-express:
    container_name: view_db
    image: mongo-express
    restart: always
    networks:
      - store-network
    ports:
      - ${DB_PORTS}:${DB_PORTS}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017/
    env_file: .env

networks:
  store-network:
volumes:
  mongo_volume: